In [ ]:
# NUMPY --> Numerical Python

import numpy as np
print(np.__version__)

2.0.2


In [ ]:
# numpy provides the support for powerful data structure named as Array

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
# Array Vs List

# SUM List
numbers = [1, 2, 3, 4, 5]
total = 0
for n in numbers:
 total += n
print(total)

15


In [ ]:
# SUM Array
numbers = np.array([1, 2, 3, 4, 5])
print(np.sum(numbers))

15


In [ ]:
import time
numbers = list(range(1, 10000000))   # 1 2 3 4 5 6 7 8 ..........................99999
total = 0
start_time = time.time() # record start time
for n in numbers:
 total += n
end_time = time.time() # record end time
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds") # .4f → means “show 4 digits after the decimal point

Total: 49999995000000
Execution Time: 2.5434 seconds


In [ ]:
numbers = np.arange(1, 10000000)
start_time = time.time()
total = np.sum(numbers)
end_time = time.time()
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds")

Total: 49999995000000
Execution Time: 0.0099 seconds


In [ ]:
# Array
# In programming, an array is a data structure used to store a collection of element
# or values, of the same data type under a single variable name.
# Array : Single Dimensional (1D) and Multi Dimensional (2D)

# How to create a 1D array
# array() used to create 1D or 2D array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
# LIST : different datatype
list1 = [10,'Yash',89.21,True]
print(list1)

# ARRAY : same data type --> convert to higher priority (auto-typecasted)
arr = np.array([10,'Yash',89.21,True])
print(arr)

[10, 'Yash', 89.21, True]
['10' 'Yash' '89.21' 'True']


In [ ]:
# shape property
# help us to determine the dimensions of an array
# For 1D array return (n,) where n is the number of elements
# For 2D array return (n,m) where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [ ]:
# Create a 2D Array
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twod)
print(twod.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
# 4x2
twod1 = np.array([[1,2],[3,4],[5,6],[7,8]])

# 5x3
twod2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

print(twod1)
print(twod1.shape)
print(twod2)
print(twod2.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)


In [ ]:
# Indexing and slicing
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[2])
print(arr[-1])
print(arr[:5])
print(arr[::-1])

30
90
[10 20 30 40 50]
[90 80 70 60 50 40 30 20 10]


In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod[0,1])
print(twod[2,0])
# show me 1st row
print(twod[0])
# show me 2nd column  [for any specific column]  arr[:,indexNumberOfThatColumn]
print(twod[:,1])
# show me the last row  [for any specific row]  arr[rowIndexNumber]
print(twod[2])

[[1 2]
 [3 4]
 [5 6]]
2
5
[1 2]
[2 4 6]
[5 6]


In [ ]:
# dtype property
# help understand what is the data type of an array

arr = np.array([10,20,30,40])
print(arr.dtype)

int64


In [ ]:
arr = np.array([10,20,30,40],dtype='i1')       # i1 = int every element 1 byte = 8bits
print(arr.dtype)                               # save memory RAM


# i2 = int2bytes  2 bytes = 16 bits     8+8
# i4 = int4bytes  4 bytes = 34 bits     8+8+8+8
# i8 = int8bytes  8 bytes = 64 bits     8+8+8+8+8+8+8+8

int8


In [ ]:
arr = np.array([10.21,20.2,30.5,40.9])
print(arr.dtype)

float64


In [ ]:
arr = np.array([True,False,False,True])
print(arr.dtype)

bool


In [ ]:
arr = np.array(['apple','banana','cherry','dragonfruit'])
print(arr.dtype)
# Unicode String --> U
# 11 : max length of string

<U11


In [ ]:
arr = np.array([10.21,20.2,30.5,40.9],dtype='int') # or int --> i / float --> f
print(arr.dtype)

int64


In [ ]:
# copy() and view()

# copy()
# a copy will create a new independent array in a diff memory location
# meaning if you make any changes in copied_array it won't effect original_array

org_arr = np.array([10,20,30,40,50,60])
print(org_arr)

copied_arr = org_arr.copy()
print(copied_arr)

# let's make some changes in copied_arr
copied_arr[1] = 200
print(copied_arr)
print(org_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[ 10 200  30  40  50  60]
[10 20 30 40 50 60]


In [ ]:
org_arr = np.array([10,20,30,40,50,60])
print(org_arr)

# view()
# a view is the representation of original_array and it shares same memory location
# meaning if you make any changes in copied_array it will effect original_array

copied_arr = org_arr.view()
print(copied_arr)

# let's make some changes in copied_arr
copied_arr[1] = 200
print(copied_arr)
print(org_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[ 10 200  30  40  50  60]
[ 10 200  30  40  50  60]


In [ ]:
org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.view()
# shares_memory() --> return True if arrays are sharing same memory location
print(np.shares_memory(org_arr,copied_arr))

True


In [ ]:
# Numpy Array Reshaping
# reshape()

# Convert 1D --> 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)  #  2x6  6x2   3x4   4x3  12x1   1x12

twod = arr.reshape(6,2)
print(twod.shape)
print(twod)

(12,)
(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
twod = arr.reshape(1,11)
print(twod.shape)
print(twod)

(1, 11)
[[ 1  2  3  4  5  6  7  8  9 10 11]]


In [ ]:
# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
# meaning 1D array will become 2D array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
# arr[np.newaxis,:]  # row vector
arr[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [ ]:
# convert 2D into 1D
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(twod)
print(twod.shape)

arr = twod.reshape(12)
print(arr.shape)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# concatenate()
# used to join 2 arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# array_split()
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(arr1,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [ ]:
# sorting()
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))

[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])     # descending order
print(np.sort(prices)[::-1])

[172 120 102  95  90  78  67  56  34  34  34  12]


In [ ]:
# Filter Operations in Numpy

arr = np.array([1,4,3,6,2,8,7,5])
print(arr)

for i in arr:
  if i>=5:
    print(i)

[1 4 3 6 2 8 7 5]
6
8
7
5


In [ ]:
# Boolean masking
res = arr>=5
print(res)

[False False False  True False  True  True  True]


In [ ]:
arr = np.array([1,4,3,6,2,8,7,5])
res = arr>=5
print(arr[res])

[6 8 7 5]


In [ ]:
# np.where(expression)
# np.where return IndexNumbers
arr = np.array([1,4,3,6,2,8,7,5])
#               0 1 2 3 4 5 6 7
res = np.where(arr>=5)
print(res)
print(arr[res])

(array([3, 5, 6, 7]),)
[6 8 7 5]


In [ ]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")
# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")
# Conditional selection
new_arr = np.where(arr > 40, arr * 2, arr)
print(f"Array after conditional selection: {new_arr}")

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [ ]:
# random module

from numpy import random
x = random.randint(100)         # 1 to 100
print(x)

98


In [ ]:
x = random.randint(90,130)         # 90 to 130
print(x)

117


In [ ]:
# rand()
# generate random float value between 0 and 1
x = random.rand()
print(x)

0.46191024062926467


In [ ]:
x = random.rand(3,3)
print(x)

y = random.rand(5)
print(y)

[[0.19848547 0.61812168 0.21949391]
 [0.52310541 0.335292   0.36482202]
 [0.24714158 0.10802856 0.41949735]]
[0.53634547 0.88855332 0.27455207 0.28846862 0.40022194]


In [ ]:
x = random.randint(100,size=(10))         # 1 to 100
print(x)

[ 1 64 29 54 71 43 94 73 94 16]


In [ ]:
x = random.randint(100,size=(10,3))         # 1 to 100
print(x)

[[85 43 18]
 [66 76 43]
 [75 15 47]
 [55 32 81]
 [98 81 51]
 [76 58 99]
 [42 50 15]
 [41 97 53]
 [50 32 48]
 [17 98 93]]


In [ ]:
# choice()
x = random.choice([5,6,7,8,9])
print(x)

8


In [ ]:
x = random.choice([5,6,7,8,9],size=(3,2))
print(x)

[[7 9]
 [5 5]
 [6 5]]


In [ ]:
# zeros()
# it will create an arrays filled with all Zeros 0's
# default data type will be Float

arr1d = np.zeros(10)
print(arr1d)

arr2d = np.zeros((5,3))
print(arr2d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# ones()
# it will create an arrays filled with all 1's
# default data type will be Float

arr = np.ones(10,dtype='i')
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50,size=(10))
x

array([32, 22, 29, 15,  6, 45,  2, 41, 19, 32])

In [ ]:
print(np.sum(x))

243


In [ ]:
# mean() returns the average
print(np.mean(x))

24.3


In [ ]:
# arange()  generate sequence of int numbers
print(np.arange(11))  # starting from zero till x-1
print(np.arange(1,21))  # starting from x till y-1
print(np.arange(1,21,2))  # starting from zero till x-1 based on intervals

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# np.unique()
# used to return unique elements as the sorted array
# delete duplicate value and sorted

x = np.unique([1,2,3,1,4,5,2,5,4,6,7,4,3,8,9,13,12,7,15,10,14])
print(x)

# 1 2 3 4 5 6 7 8 9 13 12 15 10 14

[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15]


In [ ]:
x = np.array([1,2,3,1,4,5,2,5,4,6,7,4,3,8,9,13,12,7,15,10,14])
uv , i = np.unique(x,return_index=True)

# unique          -->  1  2  3  4  5  6  7  8   9  10 12 13 14 15
# index numbers   -->  0  1  2  4  5  9  10 13 14  19 16 15 20 18

print(uv)
print(i)

[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15]
[ 0  1  2  4  5  9 10 13 14 19 16 15 20 18]


In [ ]:
# argsort() --> reorder based on original appearance
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 12, 15, 10, 14])

In [ ]:
x = np.array([1,2,3,1,4,5,2,5,4,6,7,4,3,8,9,13,12,7,15,10,14])
uv , i = np.unique(x,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 12, 15, 10, 14])

In [ ]:
# Numpy Broadcasting
arr1 = np.array([7,6,4])
arr2 = np.array([3,5,1])
print(arr1*arr2)

[21 30  4]


In [ ]:
# Let's try performing arithmetic operations b/w uncompatible shapes
arr1 = np.array([7,6,4])
arr2 = np.array([3,5])
print(arr1*arr2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# cases where there will be no broadcasting error
# if anyone of them is 1

arr1 = np.array([7,6,4])
arr2 = np.array([3])
print(arr1*arr2)

[21 18 12]
